/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedProjectsIndexRouteImport } from './routes/_protected/projects/index'
import { Route as ProtectedDocumentsIndexRouteImport } from './routes/_protected/documents/index'
import { Route as ProtectedProjectsProjectIdIndexRouteImport } from './routes/_protected/projects/$projectId/index'
import { Route as ProtectedProjectsProjectIdPodcastsIndexRouteImport } from './routes/_protected/projects/$projectId/podcasts/index'
import { Route as ProtectedProjectsProjectIdMediaTypeMediaIdIndexRouteImport } from './routes/_protected/projects/$projectId/$mediaType/$mediaId/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ProtectedProjectsIndexRoute = ProtectedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedDocumentsIndexRoute = ProtectedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedProjectsProjectIdIndexRoute =
  ProtectedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedProjectsProjectIdPodcastsIndexRoute =
  ProtectedProjectsProjectIdPodcastsIndexRouteImport.update({
    id: '/projects/$projectId/podcasts/',
    path: '/projects/$projectId/podcasts/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute =
  ProtectedProjectsProjectIdMediaTypeMediaIdIndexRouteImport.update({
    id: '/projects/$projectId/$mediaType/$mediaId/',
    path: '/projects/$projectId/$mediaType/$mediaId/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/documents': typeof ProtectedDocumentsIndexRoute
  '/projects': typeof ProtectedProjectsIndexRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdIndexRoute
  '/projects/$projectId/podcasts': typeof ProtectedProjectsProjectIdPodcastsIndexRoute
  '/projects/$projectId/$mediaType/$mediaId': typeof ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/documents': typeof ProtectedDocumentsIndexRoute
  '/projects': typeof ProtectedProjectsIndexRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdIndexRoute
  '/projects/$projectId/podcasts': typeof ProtectedProjectsProjectIdPodcastsIndexRoute
  '/projects/$projectId/$mediaType/$mediaId': typeof ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_protected/documents/': typeof ProtectedDocumentsIndexRoute
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
  '/_protected/projects/$projectId/': typeof ProtectedProjectsProjectIdIndexRoute
  '/_protected/projects/$projectId/podcasts/': typeof ProtectedProjectsProjectIdPodcastsIndexRoute
  '/_protected/projects/$projectId/$mediaType/$mediaId/': typeof ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/documents'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/podcasts'
    | '/projects/$projectId/$mediaType/$mediaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/documents'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/podcasts'
    | '/projects/$projectId/$mediaType/$mediaId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_protected/documents/'
    | '/_protected/projects/'
    | '/_protected/projects/$projectId/'
    | '/_protected/projects/$projectId/podcasts/'
    | '/_protected/projects/$projectId/$mediaType/$mediaId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedProjectsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/documents/': {
      id: '/_protected/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ProtectedDocumentsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/projects/$projectId/': {
      id: '/_protected/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/projects/$projectId/podcasts/': {
      id: '/_protected/projects/$projectId/podcasts/'
      path: '/projects/$projectId/podcasts'
      fullPath: '/projects/$projectId/podcasts'
      preLoaderRoute: typeof ProtectedProjectsProjectIdPodcastsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/projects/$projectId/$mediaType/$mediaId/': {
      id: '/_protected/projects/$projectId/$mediaType/$mediaId/'
      path: '/projects/$projectId/$mediaType/$mediaId'
      fullPath: '/projects/$projectId/$mediaType/$mediaId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdMediaTypeMediaIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedDocumentsIndexRoute: typeof ProtectedDocumentsIndexRoute
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
  ProtectedProjectsProjectIdIndexRoute: typeof ProtectedProjectsProjectIdIndexRoute
  ProtectedProjectsProjectIdPodcastsIndexRoute: typeof ProtectedProjectsProjectIdPodcastsIndexRoute
  ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute: typeof ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedDocumentsIndexRoute: ProtectedDocumentsIndexRoute,
  ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
  ProtectedProjectsProjectIdIndexRoute: ProtectedProjectsProjectIdIndexRoute,
  ProtectedProjectsProjectIdPodcastsIndexRoute:
    ProtectedProjectsProjectIdPodcastsIndexRoute,
  ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute:
    ProtectedProjectsProjectIdMediaTypeMediaIdIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
