/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedVoiceoversIndexRouteImport } from './routes/_protected/voiceovers/index'
import { Route as ProtectedPodcastsIndexRouteImport } from './routes/_protected/podcasts/index'
import { Route as ProtectedInfographicsIndexRouteImport } from './routes/_protected/infographics/index'
import { Route as ProtectedDocumentsIndexRouteImport } from './routes/_protected/documents/index'
import { Route as ProtectedVoiceoversVoiceoverIdRouteImport } from './routes/_protected/voiceovers/$voiceoverId'
import { Route as ProtectedPodcastsPodcastIdRouteImport } from './routes/_protected/podcasts/$podcastId'
import { Route as ProtectedInfographicsInfographicIdRouteImport } from './routes/_protected/infographics/$infographicId'
import { Route as ProtectedDocumentsDocumentIdRouteImport } from './routes/_protected/documents/$documentId'
import { Route as ProtectedAdminActivityRouteImport } from './routes/_protected/admin/activity'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedVoiceoversIndexRoute =
  ProtectedVoiceoversIndexRouteImport.update({
    id: '/voiceovers/',
    path: '/voiceovers/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedPodcastsIndexRoute = ProtectedPodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedInfographicsIndexRoute =
  ProtectedInfographicsIndexRouteImport.update({
    id: '/infographics/',
    path: '/infographics/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedDocumentsIndexRoute = ProtectedDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedVoiceoversVoiceoverIdRoute =
  ProtectedVoiceoversVoiceoverIdRouteImport.update({
    id: '/voiceovers/$voiceoverId',
    path: '/voiceovers/$voiceoverId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedPodcastsPodcastIdRoute =
  ProtectedPodcastsPodcastIdRouteImport.update({
    id: '/podcasts/$podcastId',
    path: '/podcasts/$podcastId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedInfographicsInfographicIdRoute =
  ProtectedInfographicsInfographicIdRouteImport.update({
    id: '/infographics/$infographicId',
    path: '/infographics/$infographicId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedDocumentsDocumentIdRoute =
  ProtectedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedAdminActivityRoute = ProtectedAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/admin/activity': typeof ProtectedAdminActivityRoute
  '/documents/$documentId': typeof ProtectedDocumentsDocumentIdRoute
  '/infographics/$infographicId': typeof ProtectedInfographicsInfographicIdRoute
  '/podcasts/$podcastId': typeof ProtectedPodcastsPodcastIdRoute
  '/voiceovers/$voiceoverId': typeof ProtectedVoiceoversVoiceoverIdRoute
  '/documents': typeof ProtectedDocumentsIndexRoute
  '/infographics': typeof ProtectedInfographicsIndexRoute
  '/podcasts': typeof ProtectedPodcastsIndexRoute
  '/voiceovers': typeof ProtectedVoiceoversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/admin/activity': typeof ProtectedAdminActivityRoute
  '/documents/$documentId': typeof ProtectedDocumentsDocumentIdRoute
  '/infographics/$infographicId': typeof ProtectedInfographicsInfographicIdRoute
  '/podcasts/$podcastId': typeof ProtectedPodcastsPodcastIdRoute
  '/voiceovers/$voiceoverId': typeof ProtectedVoiceoversVoiceoverIdRoute
  '/documents': typeof ProtectedDocumentsIndexRoute
  '/infographics': typeof ProtectedInfographicsIndexRoute
  '/podcasts': typeof ProtectedPodcastsIndexRoute
  '/voiceovers': typeof ProtectedVoiceoversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_protected/admin/activity': typeof ProtectedAdminActivityRoute
  '/_protected/documents/$documentId': typeof ProtectedDocumentsDocumentIdRoute
  '/_protected/infographics/$infographicId': typeof ProtectedInfographicsInfographicIdRoute
  '/_protected/podcasts/$podcastId': typeof ProtectedPodcastsPodcastIdRoute
  '/_protected/voiceovers/$voiceoverId': typeof ProtectedVoiceoversVoiceoverIdRoute
  '/_protected/documents/': typeof ProtectedDocumentsIndexRoute
  '/_protected/infographics/': typeof ProtectedInfographicsIndexRoute
  '/_protected/podcasts/': typeof ProtectedPodcastsIndexRoute
  '/_protected/voiceovers/': typeof ProtectedVoiceoversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/activity'
    | '/documents/$documentId'
    | '/infographics/$infographicId'
    | '/podcasts/$podcastId'
    | '/voiceovers/$voiceoverId'
    | '/documents'
    | '/infographics'
    | '/podcasts'
    | '/voiceovers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/activity'
    | '/documents/$documentId'
    | '/infographics/$infographicId'
    | '/podcasts/$podcastId'
    | '/voiceovers/$voiceoverId'
    | '/documents'
    | '/infographics'
    | '/podcasts'
    | '/voiceovers'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/dashboard'
    | '/_public/login'
    | '/_public/register'
    | '/_protected/admin/activity'
    | '/_protected/documents/$documentId'
    | '/_protected/infographics/$infographicId'
    | '/_protected/podcasts/$podcastId'
    | '/_protected/voiceovers/$voiceoverId'
    | '/_protected/documents/'
    | '/_protected/infographics/'
    | '/_protected/podcasts/'
    | '/_protected/voiceovers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/voiceovers/': {
      id: '/_protected/voiceovers/'
      path: '/voiceovers'
      fullPath: '/voiceovers'
      preLoaderRoute: typeof ProtectedVoiceoversIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/podcasts/': {
      id: '/_protected/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof ProtectedPodcastsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/infographics/': {
      id: '/_protected/infographics/'
      path: '/infographics'
      fullPath: '/infographics'
      preLoaderRoute: typeof ProtectedInfographicsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/documents/': {
      id: '/_protected/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ProtectedDocumentsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/voiceovers/$voiceoverId': {
      id: '/_protected/voiceovers/$voiceoverId'
      path: '/voiceovers/$voiceoverId'
      fullPath: '/voiceovers/$voiceoverId'
      preLoaderRoute: typeof ProtectedVoiceoversVoiceoverIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/podcasts/$podcastId': {
      id: '/_protected/podcasts/$podcastId'
      path: '/podcasts/$podcastId'
      fullPath: '/podcasts/$podcastId'
      preLoaderRoute: typeof ProtectedPodcastsPodcastIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/infographics/$infographicId': {
      id: '/_protected/infographics/$infographicId'
      path: '/infographics/$infographicId'
      fullPath: '/infographics/$infographicId'
      preLoaderRoute: typeof ProtectedInfographicsInfographicIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/documents/$documentId': {
      id: '/_protected/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof ProtectedDocumentsDocumentIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/admin/activity': {
      id: '/_protected/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof ProtectedAdminActivityRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedAdminActivityRoute: typeof ProtectedAdminActivityRoute
  ProtectedDocumentsDocumentIdRoute: typeof ProtectedDocumentsDocumentIdRoute
  ProtectedInfographicsInfographicIdRoute: typeof ProtectedInfographicsInfographicIdRoute
  ProtectedPodcastsPodcastIdRoute: typeof ProtectedPodcastsPodcastIdRoute
  ProtectedVoiceoversVoiceoverIdRoute: typeof ProtectedVoiceoversVoiceoverIdRoute
  ProtectedDocumentsIndexRoute: typeof ProtectedDocumentsIndexRoute
  ProtectedInfographicsIndexRoute: typeof ProtectedInfographicsIndexRoute
  ProtectedPodcastsIndexRoute: typeof ProtectedPodcastsIndexRoute
  ProtectedVoiceoversIndexRoute: typeof ProtectedVoiceoversIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedAdminActivityRoute: ProtectedAdminActivityRoute,
  ProtectedDocumentsDocumentIdRoute: ProtectedDocumentsDocumentIdRoute,
  ProtectedInfographicsInfographicIdRoute:
    ProtectedInfographicsInfographicIdRoute,
  ProtectedPodcastsPodcastIdRoute: ProtectedPodcastsPodcastIdRoute,
  ProtectedVoiceoversVoiceoverIdRoute: ProtectedVoiceoversVoiceoverIdRoute,
  ProtectedDocumentsIndexRoute: ProtectedDocumentsIndexRoute,
  ProtectedInfographicsIndexRoute: ProtectedInfographicsIndexRoute,
  ProtectedPodcastsIndexRoute: ProtectedPodcastsIndexRoute,
  ProtectedVoiceoversIndexRoute: ProtectedVoiceoversIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
