import { Effect, Layer } from 'effect';
import type { UIMessageChunk } from 'ai';
import { LLMError, type LLMRateLimitError } from '../errors';
import {
  LLM,
  type GenerateOptions,
  type GenerateResult,
  type LLMService,
} from '../llm/service';

export const DEFAULT_MOCK_SCRIPT = {
  title: 'Test Podcast Title',
  description: 'A test podcast description generated by the mock LLM.',
  summary: 'This is a test summary of the podcast content.',
  tags: ['test', 'podcast', 'mock'],
  segments: [
    {
      speaker: 'host',
      line: 'Welcome to the show! Today we have an exciting topic.',
      index: 0,
    },
    {
      speaker: 'cohost',
      line: 'Thanks for having me. I am looking forward to discussing this.',
      index: 1,
    },
    {
      speaker: 'host',
      line: 'Let us dive right into the key points.',
      index: 2,
    },
    { speaker: 'cohost', line: 'That is a great place to start.', index: 3 },
  ],
};

export interface MockLLMGenerateInput {
  readonly system?: string;
  readonly prompt: string;
  readonly model?: string;
  readonly maxTokens?: number;
  readonly temperature?: number;
}

export type MockLLMGenerate = (
  options: MockLLMGenerateInput,
) => Effect.Effect<GenerateResult<unknown>, LLMError | LLMRateLimitError>;

export interface MockLLMOptions {
  delay?: number;
  response?: unknown;
  stream?: ReadableStream<UIMessageChunk>;
  usage?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
  };
  errorMessage?: string;
  generate?: MockLLMGenerate;
  streamText?: LLMService['streamText'];
}

export function createMockLLMService(options: MockLLMOptions = {}): LLMService {
  const stream =
    options.stream ??
    new ReadableStream<UIMessageChunk>({
      start(controller) {
        controller.close();
      },
    });

  const defaultGenerate = <T>(): Effect.Effect<
    GenerateResult<T>,
    LLMError | LLMRateLimitError
  > =>
    Effect.gen(function* () {
      if (options.delay) {
        yield* Effect.sleep(options.delay);
      }

      if (options.errorMessage) {
        return yield* Effect.fail(
          new LLMError({ message: options.errorMessage }),
        );
      }

      return {
        object: (options.response ?? DEFAULT_MOCK_SCRIPT) as T,
        usage: options.usage ?? {
          inputTokens: 100,
          outputTokens: 200,
          totalTokens: 300,
        },
      };
    });

  const defaultStreamText = () =>
    Effect.gen(function* () {
      if (options.delay) {
        yield* Effect.sleep(options.delay);
      }

      if (options.errorMessage) {
        return yield* Effect.fail(
          new LLMError({ message: options.errorMessage }),
        );
      }

      return stream;
    });

  return {
    generate: options.generate
      ? <T>(generateOptions: GenerateOptions<T>) =>
          options.generate!({
            system: generateOptions.system,
            prompt: generateOptions.prompt,
            model: generateOptions.model,
            maxTokens: generateOptions.maxTokens,
            temperature: generateOptions.temperature,
          }).pipe(
            Effect.map(
              (result) =>
                ({
                  object: result.object as T,
                  usage: result.usage,
                }) satisfies GenerateResult<T>,
            ),
          )
      : defaultGenerate,
    streamText: options.streamText ?? defaultStreamText,
  };
}

export function createMockLLM(options: MockLLMOptions = {}): Layer.Layer<LLM> {
  const service = createMockLLMService(options);
  return Layer.succeed(LLM, service);
}

export const MockLLMLive = createMockLLM();

export const MockLLMWithLatency = createMockLLM({ delay: 10_000 });
