import { Layer, Effect } from 'effect';
import type { UIMessageChunk } from 'ai';
import {
  LLM,
  type LLMService,
  type GenerateResult,
  LLMError,
  type LLMRateLimitError,
} from '..';

export const DEFAULT_MOCK_SCRIPT = {
  title: 'Test Podcast Title',
  description: 'A test podcast description generated by the mock LLM.',
  summary: 'This is a test summary of the podcast content.',
  tags: ['test', 'podcast', 'mock'],
  segments: [
    {
      speaker: 'host',
      line: 'Welcome to the show! Today we have an exciting topic.',
      index: 0,
    },
    {
      speaker: 'cohost',
      line: 'Thanks for having me. I am looking forward to discussing this.',
      index: 1,
    },
    {
      speaker: 'host',
      line: 'Let us dive right into the key points.',
      index: 2,
    },
    { speaker: 'cohost', line: 'That is a great place to start.', index: 3 },
  ],
};

export interface MockLLMOptions {
  delay?: number;
  response?: unknown;
  stream?: ReadableStream<UIMessageChunk>;
  usage?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
  };
  errorMessage?: string;
}

export function createMockLLM(options: MockLLMOptions = {}): Layer.Layer<LLM> {
  const stream =
    options.stream ??
    new ReadableStream<UIMessageChunk>({
      start(controller) {
        controller.close();
      },
    });

  const service: LLMService = {
    generate: <T>(): Effect.Effect<
      GenerateResult<T>,
      LLMError | LLMRateLimitError
    > =>
      Effect.gen(function* () {
        if (options.delay) {
          yield* Effect.sleep(options.delay);
        }

        if (options.errorMessage) {
          return yield* Effect.fail(
            new LLMError({ message: options.errorMessage }),
          );
        }

        return {
          object: (options.response ?? DEFAULT_MOCK_SCRIPT) as T,
          usage: options.usage ?? {
            inputTokens: 100,
            outputTokens: 200,
            totalTokens: 300,
          },
        };
      }),
    streamText: () =>
      Effect.gen(function* () {
        if (options.delay) {
          yield* Effect.sleep(options.delay);
        }

        if (options.errorMessage) {
          return yield* Effect.fail(
            new LLMError({ message: options.errorMessage }),
          );
        }

        return stream;
      }),
  };

  return Layer.succeed(LLM, service);
}

export const MockLLMLive = createMockLLM();

export const MockLLMWithLatency = createMockLLM({ delay: 10_000 });
